name: {{name.snakeCase()}}
description: "The project for {{name.pascalCase()}}"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
# Name File APK
#  {{name.snakeCase()}}_1.0.0.apk
#  ### version
#  * Eg: 1.0.0:
#1: Big function
#0: Middle function & important Bug
#0: small bug


environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  get_it: ^7.6.7
  go_router: ^14.1.3

  ui_core:
    path: packages/ancestor_cores/ui_core

  storage_core:
    path: packages/ancestor_cores/storage_core

  flutter_core:
    path: packages/ancestor_cores/flutter_core

  dart_core:
    path: packages/ancestor_cores/dart_core

  flutter_localization: ^0.2.0
  flutter_bloc: ^8.1.3
  gap: ^3.0.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  hydrated_bloc: ^9.1.4
  replay_bloc: ^0.2.6
  bloc_concurrency: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  lint: ^2.3.0 # plugin for Effective Dart (Clean code)
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.5.2
  test: ^1.25.2
  bloc_test: ^9.1.7
  integration_test:
    sdk: flutter
  mockito: ^5.4.1

#Learn more: https://pub.dev/packages/flutter_launcher_icons
#run: flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/i18n/
